# Generated by Django 3.2.14 on 2022-07-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_for_others',
            field=models.BooleanField(default=False),
        ),
    ]
