# Generated by Django 3.2.14 on 2022-08-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_for_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='avoid plastic cover'),
        ),
    ]
