# Generated by Django 3.2.14 on 2022-08-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(default='avoid plastic cover', null=True),
        ),
    ]
