# Generated by Django 3.2.14 on 2022-08-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_canceled_orders_reason_for_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='canceled_orders',
            name='cancel_date',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
