# Generated by Django 3.2.14 on 2022-08-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canceled_orders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
