# Generated by Django 3.2.14 on 2022-08-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220729_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='state',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
