# Generated by Django 3.2.14 on 2022-08-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_user_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
