# Generated by Django 3.2.14 on 2022-08-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_coupons_user_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
