# Generated by Django 3.2.14 on 2022-08-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
