# Generated by Django 3.2.14 on 2022-08-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_offer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(default=True),
        ),
    ]
