# Generated by Django 3.2.14 on 2022-08-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20220822_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='banner_text',
            field=models.TextField(null=True),
        ),
    ]
